"""Core schema and runtime helpers for Agent Lexicon."""

from __future__ import annotations

from .cache import (
    DEFAULT_RUNTIME_CACHE_SIZE,
    LexiconRuntimeCache,
    RuntimeCacheStats,
    clear_runtime_cache,
    default_runtime_cache,
    get_cached_resolver,
    get_cached_surface_matcher,
    get_cached_tool_guard,
    load_cached_lexicon,
    runtime_cache_stats,
)
from .snapshots import (
    LEXICON_FINGERPRINT_ALGORITHM,
    LEXICON_SNAPSHOT_REF_PREFIX,
    LexiconFingerprint,
    LexiconSnapshotMetadata,
    fingerprint_lexicon,
    lexicon_runtime_metadata,
    lexicon_snapshot_metadata,
    lexicon_snapshot_ref,
)
from .loader import AgentLexiconLoadError, lexicon_from_dict, load_lexicon, loads_lexicon
from .files import atomic_write_text
from .linter import (
    LexiconLintCode,
    LexiconLintFinding,
    LexiconLintReport,
    LexiconLintSeverity,
    lint_lexicon,
    lint_lexicon_file,
)
from .matcher import (
    SurfaceEntry,
    SurfaceKind,
    SurfaceMatch,
    SurfaceMatcher,
    build_surface_matcher,
    find_surface_matches,
)
from .models import (
    AgentLexiconModelError,
    Alias,
    EvidenceKind,
    EvidenceSpan,
    Lexicon,
    ProposalCandidate,
    ProposalKind,
    ProposalStatus,
    ResolutionAction,
    ResolutionCandidate,
    ResolutionDecision,
    ResolutionMatch,
    ResolutionStatus,
    RiskLevel,
    Scope,
    Term,
    ToolGuardAction,
    ToolGuardDecision,
    ToolGuardStatus,
)
from .resolver import LexiconResolver, resolve_text
from .tool_guard import ToolGuard, guard_tool_call

__all__ = [
    "AgentLexiconLoadError",
    "DEFAULT_RUNTIME_CACHE_SIZE",
    "LEXICON_FINGERPRINT_ALGORITHM",
    "LEXICON_SNAPSHOT_REF_PREFIX",
    "LexiconFingerprint",
    "LexiconSnapshotMetadata",
    "LexiconRuntimeCache",
    "RuntimeCacheStats",
    "clear_runtime_cache",
    "default_runtime_cache",
    "fingerprint_lexicon",
    "lexicon_runtime_metadata",
    "lexicon_snapshot_metadata",
    "lexicon_snapshot_ref",
    "get_cached_resolver",
    "get_cached_surface_matcher",
    "get_cached_tool_guard",
    "load_cached_lexicon",
    "runtime_cache_stats",
    "AgentLexiconModelError",
    "atomic_write_text",
    "Alias",
    "EvidenceKind",
    "EvidenceSpan",
    "Lexicon",
    "LexiconLintCode",
    "LexiconLintFinding",
    "LexiconLintReport",
    "LexiconLintSeverity",
    "LexiconResolver",
    "ProposalCandidate",
    "ProposalKind",
    "ProposalStatus",
    "ResolutionAction",
    "ResolutionCandidate",
    "ResolutionDecision",
    "ResolutionMatch",
    "ResolutionStatus",
    "RiskLevel",
    "SurfaceEntry",
    "SurfaceKind",
    "SurfaceMatch",
    "SurfaceMatcher",
    "Scope",
    "Term",
    "ToolGuard",
    "ToolGuardAction",
    "ToolGuardDecision",
    "ToolGuardStatus",
    "guard_tool_call",
    "lexicon_from_dict",
    "load_lexicon",
    "lint_lexicon",
    "lint_lexicon_file",
    "build_surface_matcher",
    "find_surface_matches",
    "loads_lexicon",
    "resolve_text",
]
