"""Agent Lexicon: shared terminology memory for AI agents."""

from __future__ import annotations

from .core import (
    AgentLexiconLoadError,
    AgentLexiconModelError,
    Alias,
    EvidenceKind,
    EvidenceSpan,
    Lexicon,
    LexiconResolver,
    ProposalCandidate,
    ProposalKind,
    ProposalStatus,
    ResolutionAction,
    ResolutionCandidate,
    ResolutionDecision,
    ResolutionMatch,
    ResolutionStatus,
    RiskLevel,
    Scope,
    SurfaceEntry,
    SurfaceKind,
    SurfaceMatch,
    SurfaceMatcher,
    Term,
    ToolGuard,
    ToolGuardAction,
    ToolGuardDecision,
    ToolGuardStatus,
    build_surface_matcher,
    find_surface_matches,
    guard_tool_call,
    lexicon_from_dict,
    load_lexicon,
    loads_lexicon,
    resolve_text,
)
from .evals import (
    BehaviorMetrics,
    EvalQueryResult,
    EvalReport,
    EvalToolCallResult,
    EvalDatasetError,
    EvalQuery,
    EvalToolCallExpectation,
    eval_query_from_dict,
    load_eval_queries,
    run_behavior_eval,
    loads_eval_queries,
)

from .scout import (
    CandidateSurfaceKind,
    ScoutCandidate,
    ScoutCandidateError,
    ScoutCandidateOccurrence,
    ScoutCandidateReport,
    discover_scout_candidates,
    existing_surfaces_from_lexicon,
)
from .ingest import (
    DEFAULT_EXCLUDE_DIRS,
    DEFAULT_INCLUDE_GLOBS,
    DEFAULT_MAX_FILE_BYTES,
    IngestDocument,
    IngestSourceKind,
    LocalIngestError,
    LocalIngestReport,
    classify_source_kind,
    discover_local_files,
    ingest_local_paths,
    read_local_document,
)


__all__ = [
    "__version__",
    "existing_surfaces_from_lexicon",
    "discover_scout_candidates",
    "ScoutCandidateReport",
    "ScoutCandidateOccurrence",
    "ScoutCandidateError",
    "ScoutCandidate",
    "CandidateSurfaceKind",
    "about",
    "AgentLexiconLoadError",
    "AgentLexiconModelError",
    "Alias",
    "EvidenceKind",
    "EvidenceSpan",
    "EvalToolCallExpectation",
    "read_local_document",
    "ingest_local_paths",
    "discover_local_files",
    "classify_source_kind",
    "LocalIngestReport",
    "LocalIngestError",
    "IngestSourceKind",
    "IngestDocument",
    "DEFAULT_MAX_FILE_BYTES",
    "DEFAULT_INCLUDE_GLOBS",
    "DEFAULT_EXCLUDE_DIRS",
    "EvalQuery",
    "BehaviorMetrics",
    "EvalQueryResult",
    "EvalReport",
    "EvalToolCallResult",
    "run_behavior_eval",
    "EvalDatasetError",
    "Lexicon",
    "LexiconResolver",
    "ProposalCandidate",
    "ProposalKind",
    "ProposalStatus",
    "ResolutionAction",
    "ResolutionCandidate",
    "ResolutionDecision",
    "ResolutionMatch",
    "ResolutionStatus",
    "RiskLevel",
    "Scope",
    "SurfaceEntry",
    "SurfaceKind",
    "SurfaceMatch",
    "SurfaceMatcher",
    "Term",
    "ToolGuard",
    "ToolGuardAction",
    "ToolGuardDecision",
    "ToolGuardStatus",
    "build_surface_matcher",
    "find_surface_matches",
    "guard_tool_call",
    "loads_eval_queries",
    "load_eval_queries",
    "eval_query_from_dict",
    "lexicon_from_dict",
    "load_lexicon",
    "loads_lexicon",
    "resolve_text",
]

__version__ = "0.1.0"


def about() -> str:
    """Return a short package description."""
    return "Agent Lexicon: shared terminology memory for AI agents."
