"""Agent Lexicon: shared terminology memory for AI agents."""

from __future__ import annotations

from .core import (
    AgentLexiconLoadError,
    AgentLexiconModelError,
    Alias,
    EvidenceKind,
    EvidenceSpan,
    Lexicon,
    LexiconResolver,
    ProposalCandidate,
    ProposalKind,
    ProposalStatus,
    ResolutionAction,
    ResolutionCandidate,
    ResolutionDecision,
    ResolutionMatch,
    ResolutionStatus,
    RiskLevel,
    Scope,
    SurfaceEntry,
    SurfaceKind,
    SurfaceMatch,
    SurfaceMatcher,
    Term,
    ToolGuard,
    ToolGuardAction,
    ToolGuardDecision,
    ToolGuardStatus,
    build_surface_matcher,
    find_surface_matches,
    guard_tool_call,
    lexicon_from_dict,
    load_lexicon,
    loads_lexicon,
    resolve_text,
)
from .evals import (
    BehaviorMetrics,
    EvalQueryResult,
    EvalReport,
    EvalToolCallResult,
    EvalDatasetError,
    EvalQuery,
    EvalToolCallExpectation,
    eval_query_from_dict,
    load_eval_queries,
    run_behavior_eval,
    loads_eval_queries,
)

__all__ = [
    "__version__",
    "about",
    "AgentLexiconLoadError",
    "AgentLexiconModelError",
    "Alias",
    "EvidenceKind",
    "EvidenceSpan",
    "EvalToolCallExpectation",
    "EvalQuery",
    "BehaviorMetrics",
    "EvalQueryResult",
    "EvalReport",
    "EvalToolCallResult",
    "run_behavior_eval",
    "EvalDatasetError",
    "Lexicon",
    "LexiconResolver",
    "ProposalCandidate",
    "ProposalKind",
    "ProposalStatus",
    "ResolutionAction",
    "ResolutionCandidate",
    "ResolutionDecision",
    "ResolutionMatch",
    "ResolutionStatus",
    "RiskLevel",
    "Scope",
    "SurfaceEntry",
    "SurfaceKind",
    "SurfaceMatch",
    "SurfaceMatcher",
    "Term",
    "ToolGuard",
    "ToolGuardAction",
    "ToolGuardDecision",
    "ToolGuardStatus",
    "build_surface_matcher",
    "find_surface_matches",
    "guard_tool_call",
    "loads_eval_queries",
    "load_eval_queries",
    "eval_query_from_dict",
    "lexicon_from_dict",
    "load_lexicon",
    "loads_lexicon",
    "resolve_text",
]

__version__ = "0.1.0"


def about() -> str:
    """Return a short package description."""
    return "Agent Lexicon: shared terminology memory for AI agents."
